FROM python:3.12-slim
WORKDIR /app

# Aquí es donde Docker busca el archivo que acabamos de crear arriba
COPY requirements.txt .

# Aquí es donde se instalan las 4 librerías que pusimos en el txt
RUN pip install --no-cache-dir -r requirements.txt

COPY ./app ./app
EXPOSE 8000

CMD ["uvicorn", "app.main:app", "--host","0.0.0.0", "--port", "8000","--reload"]