services:
  myapi:
    build: .
    container_name: server_examen
    ports:
      - "5000:8000"
    volumes:
      - .:/app

  redis-db:
    image: redis:alpine
    container_name: redis_examen
    ports:
      - "6379:6379"